import { type GitHubClient } from "./client.js";

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface ProcessedComment {
  id: number;
  type: "review_comment" | "issue_comment" | "review";
  user: string;
  isBot: boolean;
  path: string | null;
  line: number | null;
  diffHunk: string | null;
  body: string;
  state?: string;
  createdAt: string;
  updatedAt: string;
  url: string;
  replies: Reply[];
  hasHumanReply: boolean;
  hasAnyReply: boolean;
  isResolved: boolean;
}

export interface Reply {
  id: number;
  user: string;
  body: string;
  createdAt: string;
  isBot: boolean;
}

export interface FilterOptions {
  botsOnly?: boolean;
  humansOnly?: boolean;
  filter?: "unresolved" | "unanswered" | null;
}

// ---------------------------------------------------------------------------
// Tracking comment
// ---------------------------------------------------------------------------

export const TRACKING_COMMENT_MARKER = "<!-- bellwether-tracking -->";

// ---------------------------------------------------------------------------
// Meta-comment filters
// ---------------------------------------------------------------------------

type MetaFilter = (user: string, body: string) => boolean;

const DEFAULT_META_FILTERS: MetaFilter[] = [
  (_user, body) => body.startsWith("> Re: comment "),
  (_user, body) => body.startsWith(TRACKING_COMMENT_MARKER),
  (user, body) => (user === "vercel[bot]" || user === "vercel") && body.startsWith("[vc]:"),
  (user, body) => (user === "supabase[bot]" || user === "supabase") && body.startsWith("[supa]:"),
  (user, body) =>
    (user === "cursor[bot]" || user === "cursor") &&
    body.startsWith("Cursor Bugbot has reviewed your changes"),
  (user, body) =>
    (user === "copilot-pull-request-reviewer[bot]" || user === "copilot-pull-request-reviewer") &&
    body.includes("Pull request overview"),
  (user, body) =>
    (user === "coderabbitai[bot]" || user === "coderabbitai") &&
    body.includes("<!-- This is an auto-generated comment: summarize by coderabbit.ai -->"),
  (user, body) =>
    (user === "sourcery-ai[bot]" || user === "sourcery-ai") &&
    body.includes("<!-- Generated by sourcery-ai[bot]:"),
  (user, body) =>
    (user === "codacy-production[bot]" || user === "codacy-production") &&
    (body.includes("Codacy's Analysis Summary") || body.includes("Coverage summary from Codacy")),
  (user, body) =>
    (user === "sonarcloud[bot]" ||
      user === "sonarcloud" ||
      user === "sonarqubecloud[bot]" ||
      user === "sonarqubecloud" ||
      user === "sonarqube-cloud-us[bot]" ||
      user === "sonarqube-cloud-us") &&
    body.includes("Quality Gate"),
  (user, body) =>
    (user === "pkg-pr-new[bot]" || user === "pkg-pr-new") && body.includes("pkg.pr.new"),
];

function isMetaComment(user: string, body: string): boolean {
  if (!body) {
    return false;
  }
  return DEFAULT_META_FILTERS.some((filter) => filter(user, body));
}

// ---------------------------------------------------------------------------
// Bot detection
// ---------------------------------------------------------------------------

const KNOWN_BOT_LOGINS = new Set([
  "cursor",
  "vercel",
  "supabase",
  "chatgpt-codex-connector",
  "github-actions",
  "Copilot",
  "copilot-pull-request-reviewer",
  "coderabbitai",
  "sourcery-ai",
  "codacy-production",
  "sonarcloud",
  "sonarqubecloud",
  "sonarqube-cloud-us",
  "pkg-pr-new",
]);

function isBot(username: string | undefined): boolean {
  if (!username) {
    return false;
  }
  return username.endsWith("[bot]") || KNOWN_BOT_LOGINS.has(username) || username.includes("bot");
}

// ---------------------------------------------------------------------------
// Body cleanup
// ---------------------------------------------------------------------------

function cleanBody(body: string | null | undefined): string {
  if (!body) {
    return "";
  }
  let cleaned = body;
  // Remove HTML comments (single and multi-line)
  cleaned = cleaned.replaceAll(/<!--[\s\S]*?-->/g, "");
  // Remove <details> blocks containing "Additional Locations"
  cleaned = cleaned.replaceAll(
    /<details>\s*<summary>\s*Additional Locations[\s\S]*?<\/details>/gi,
    "",
  );
  // Remove <p> blocks containing cursor.com links
  cleaned = cleaned.replaceAll(/<p>\s*<a [^>]*cursor\.com[\s\S]*?<\/p>/gi, "");
  // Collapse runs of 3+ newlines into 2
  cleaned = cleaned.replaceAll(/\n{3,}/g, "\n\n");
  return cleaned.trim();
}

// ---------------------------------------------------------------------------
// Fetch & process
// ---------------------------------------------------------------------------

interface RawReviewComment {
  id: number;
  user?: { login: string };
  body: string;
  path: string;
  line: number | null;
  original_line: number | null;
  diff_hunk: string | null;
  created_at: string;
  updated_at: string;
  html_url: string;
  in_reply_to_id?: number;
}

interface RawIssueComment {
  id: number;
  user?: { login: string };
  body: string;
  created_at: string;
  updated_at: string;
  html_url: string;
}

interface RawReview {
  id: number;
  user?: { login: string };
  body: string | null;
  state: string;
  submitted_at: string;
  html_url: string;
}

export interface RawCommentData {
  reviewComments: RawReviewComment[];
  issueComments: RawIssueComment[];
  reviews: RawReview[];
}

export async function fetchPRComments(
  owner: string,
  repo: string,
  prNumber: number,
  octokit: GitHubClient,
): Promise<RawCommentData> {
  const [reviewComments, issueComments, reviews] = await Promise.all([
    octokit.paginate(octokit.rest.pulls.listReviewComments, {
      owner,
      repo,
      pull_number: prNumber,
      per_page: 100,
    }) as Promise<RawReviewComment[]>,
    octokit.paginate(octokit.rest.issues.listComments, {
      owner,
      repo,
      issue_number: prNumber,
      per_page: 100,
    }) as Promise<RawIssueComment[]>,
    octokit.paginate(octokit.rest.pulls.listReviews, {
      owner,
      repo,
      pull_number: prNumber,
      per_page: 100,
    }) as Promise<RawReview[]>,
  ]);

  return { reviewComments, issueComments, reviews };
}

export function processComments(data: RawCommentData): ProcessedComment[] {
  const { reviewComments, issueComments, reviews } = data;

  // Build reply map
  const repliesMap = new Map<number, Reply[]>();
  for (const comment of reviewComments) {
    if (comment.in_reply_to_id) {
      if (!repliesMap.has(comment.in_reply_to_id)) {
        repliesMap.set(comment.in_reply_to_id, []);
      }
      repliesMap.get(comment.in_reply_to_id)!.push({
        id: comment.id,
        user: comment.user?.login ?? "unknown",
        body: cleanBody(comment.body),
        createdAt: comment.created_at,
        isBot: isBot(comment.user?.login),
      });
    }
  }

  const processed: ProcessedComment[] = [];

  // Review comments (inline code comments)
  for (const comment of reviewComments) {
    if (comment.in_reply_to_id) {
      continue;
    }
    if (isMetaComment(comment.user?.login ?? "", comment.body)) {
      continue;
    }

    const replies = repliesMap.get(comment.id) ?? [];
    const hasHumanReply = replies.some((r) => !r.isBot);
    const hasAnyReply = replies.length > 0;

    processed.push({
      id: comment.id,
      type: "review_comment",
      user: comment.user?.login ?? "unknown",
      isBot: isBot(comment.user?.login),
      path: comment.path,
      // oxlint-disable-next-line typescript/prefer-nullish-coalescing -- 0 is "no line", intentional falsy check
      line: comment.line || comment.original_line,
      diffHunk: comment.diff_hunk ?? null,
      body: cleanBody(comment.body),
      createdAt: comment.created_at,
      updatedAt: comment.updated_at,
      url: comment.html_url,
      replies,
      hasHumanReply,
      hasAnyReply,
      isResolved: false,
    });
  }

  // Build set of issue comment IDs that have been replied to
  // (via old-style "> Re: comment {id}" or new-style tracking comment)
  const repliedIssueCommentIds = new Set<number>();
  for (const ic of issueComments) {
    const oldMatch = ic.body.match(/^> Re: comment (\d+)/);
    if (oldMatch) {
      repliedIssueCommentIds.add(Number(oldMatch[1]));
    }
    if (ic.body.startsWith(TRACKING_COMMENT_MARKER)) {
      for (const m of ic.body.matchAll(/- Re: comment (\d+)/g)) {
        repliedIssueCommentIds.add(Number(m[1]));
      }
    }
  }

  // Issue comments (general PR comments)
  for (const comment of issueComments) {
    if (isMetaComment(comment.user?.login ?? "", comment.body)) {
      continue;
    }

    processed.push({
      id: comment.id,
      type: "issue_comment",
      user: comment.user?.login ?? "unknown",
      isBot: isBot(comment.user?.login),
      path: null,
      line: null,
      diffHunk: null,
      body: cleanBody(comment.body),
      createdAt: comment.created_at,
      updatedAt: comment.updated_at,
      url: comment.html_url,
      replies: [],
      hasHumanReply: false,
      hasAnyReply: repliedIssueCommentIds.has(comment.id),
      isResolved: false,
    });
  }

  // Reviews (only human, with body)
  for (const review of reviews) {
    if (isBot(review.user?.login)) {
      continue;
    }
    if (isMetaComment(review.user?.login ?? "", review.body ?? "")) {
      continue;
    }
    if (!review.body?.trim()) {
      continue;
    }

    processed.push({
      id: review.id,
      type: "review",
      user: review.user?.login ?? "unknown",
      isBot: false,
      path: null,
      line: null,
      diffHunk: null,
      body: cleanBody(review.body),
      state: review.state,
      createdAt: review.submitted_at,
      updatedAt: review.submitted_at,
      url: review.html_url,
      replies: [],
      hasHumanReply: false,
      hasAnyReply: false,
      isResolved: review.state === "APPROVED" || review.state === "DISMISSED",
    });
  }

  processed.sort((a, b) => new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime());

  return processed;
}

export function filterComments(
  comments: ProcessedComment[],
  options: FilterOptions,
): ProcessedComment[] {
  let filtered = comments;

  if (options.botsOnly) {
    filtered = filtered.filter((c) => c.isBot);
  } else if (options.humansOnly) {
    filtered = filtered.filter((c) => !c.isBot);
  }

  if (options.filter === "unresolved") {
    filtered = filtered.filter((c) => !(c.isResolved || c.hasHumanReply));
  } else if (options.filter === "unanswered") {
    filtered = filtered.filter((c) => !c.hasAnyReply);
  }

  return filtered;
}

// ---------------------------------------------------------------------------
// Reply & resolve
// ---------------------------------------------------------------------------

export async function replyToComment(
  owner: string,
  repo: string,
  prNumber: number,
  commentId: number,
  message: string,
  octokit: GitHubClient,
): Promise<{ html_url: string }> {
  // Try review comment reply endpoint first
  try {
    const { data } = await octokit.rest.pulls.createReplyForReviewComment({
      owner,
      repo,
      pull_number: prNumber,
      comment_id: commentId,
      body: message,
    });
    return { html_url: data.html_url };
  } catch (error: unknown) {
    if ((error as { status?: number }).status !== 404) {
      throw error;
    }
  }

  // 404 means this is an issue comment, not a review comment.
  // Consolidate into a single tracking comment with bullet list.
  const existingComments = await octokit.paginate(octokit.rest.issues.listComments, {
    owner,
    repo,
    issue_number: prNumber,
    per_page: 100,
  });

  // Pick the most recently updated tracking comment if multiple exist
  const trackingComment = (existingComments as RawIssueComment[])
    .filter((c) => c.body.startsWith(TRACKING_COMMENT_MARKER))
    .toSorted((a, b) => new Date(b.updated_at).getTime() - new Date(a.updated_at).getTime())[0];
  const newBullet = `- Re: comment ${commentId} — ${message}`;

  if (trackingComment) {
    // Re-fetch the latest body to avoid stale read-modify-write
    const { data: fresh } = await octokit.rest.issues.getComment({
      owner,
      repo,
      comment_id: trackingComment.id,
    });

    const updatedBody = `${fresh.body}\n${newBullet}`;
    const { data: updated } = await octokit.rest.issues.updateComment({
      owner,
      repo,
      comment_id: trackingComment.id,
      body: updatedBody,
    });

    return { html_url: updated.html_url };
  }

  // Create new tracking comment
  const { data: created } = await octokit.rest.issues.createComment({
    owner,
    repo,
    issue_number: prNumber,
    body: `${TRACKING_COMMENT_MARKER}\n**Handled comments:**\n${newBullet}`,
  });

  return { html_url: created.html_url };
}

export async function resolveThread(
  owner: string,
  repo: string,
  prNumber: number,
  commentId: number,
  octokit: GitHubClient,
): Promise<
  | { resolved: true; threadId: string }
  | { alreadyResolved: true; threadId: string }
  | { skipped: true; reason: string }
> {
  const query = `
    query($owner: String!, $repo: String!, $pr: Int!, $cursor: String) {
      repository(owner: $owner, name: $repo) {
        pullRequest(number: $pr) {
          reviewThreads(first: 100, after: $cursor) {
            pageInfo { hasNextPage endCursor }
            nodes {
              id
              isResolved
              comments(first: 1) {
                nodes { databaseId }
              }
            }
          }
        }
      }
    }
  `;

  interface ReviewThreadNode {
    id: string;
    isResolved: boolean;
    comments: { nodes: { databaseId: number }[] };
  }

  interface GraphQLResponse {
    repository?: {
      pullRequest?: {
        reviewThreads?: {
          pageInfo: { hasNextPage: boolean; endCursor: string | null };
          nodes: ReviewThreadNode[];
        };
      };
    };
  }

  let cursor: string | null = null;
  let thread: ReviewThreadNode | null = null;

  while (!thread) {
    const data: GraphQLResponse = await octokit.graphql<GraphQLResponse>(query, {
      owner,
      repo,
      pr: prNumber,
      cursor,
    });

    const reviewThreads = data.repository?.pullRequest?.reviewThreads;
    if (!reviewThreads) {
      break;
    }

    thread =
      reviewThreads.nodes.find((t: ReviewThreadNode) =>
        t.comments.nodes.some((c: { databaseId: number }) => c.databaseId === commentId),
      ) ?? null;

    if (!thread && reviewThreads.pageInfo.hasNextPage) {
      cursor = reviewThreads.pageInfo.endCursor;
    } else {
      break;
    }
  }

  if (!thread) {
    return { skipped: true, reason: "not a review comment thread" };
  }

  if (thread.isResolved) {
    return { alreadyResolved: true, threadId: thread.id };
  }

  const mutation = `
    mutation($threadId: ID!) {
      resolveReviewThread(input: { threadId: $threadId }) {
        thread { id isResolved }
      }
    }
  `;

  await octokit.graphql(mutation, { threadId: thread.id });

  return { resolved: true, threadId: thread.id };
}
